'use client'
import {useEffect,useMemo,useRef,useState} from 'react'
import {LoaderCircle,Play,Square,Layers3,CheckCircle2,AlertTriangle,RefreshCw} from 'lucide-react'

function flatten(plan:any){const out:any[]=[];for(let ci=0;ci<(plan?.chapters||[]).length;ci++)for(let si=0;si<(plan.chapters[ci].scenes||[]).length;si++)for(let shi=0;shi<(plan.chapters[ci].scenes[si].shots||[]).length;shi++){const sh=plan.chapters[ci].scenes[si].shots[shi];out.push({shotId:sh.id,chapterIndex:ci,sceneIndex:si,shotIndex:shi,shot:sh})}return out}

export default function ProductionQueue({projectId,plan,onApply,onError}:{projectId:string;plan:any;onApply:(next:any)=>void;onError:(s:string)=>void}){
 const [running,setRunning]=useState(false); const [concurrency,setConcurrency]=useState(3); const [retrying,setRetrying]=useState(false); const timer=useRef<any>(null)
 const shots=useMemo(()=>flatten(plan),[plan])
 const stats=useMemo(()=>{let q=0,r=0,c=0,f=0;for(const x of shots){const s=x.shot.productionJob?.status;if(s==='queued')q++;else if(s==='running')r++;else if(s==='complete'||x.shot.status==='complete')c++;else if(s==='failed'||x.shot.status==='failed')f++}return {q,r,c,f,total:shots.length}},[shots])
 const failures=useMemo(()=>shots.filter(x=>x.shot.productionJob?.status==='failed'||x.shot.status==='failed').map(x=>({id:x.shot.id,label:`Chapter ${x.chapterIndex+1} · Scene ${x.sceneIndex+1} · Shot ${x.shotIndex+1}`,error:x.shot.productionJob?.error||'No failure detail was recorded.'})),[shots])
 const queue=async()=>{try{const r=await fetch('/api/production/queue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,plan,concurrency})});const d=await r.json();if(!r.ok)throw new Error(d.error);onApply(d.plan)}catch(e:any){onError(e.message||'Could not queue production.')}}
 const tick=async()=>{try{const r=await fetch('/api/production/tick',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,plan:planRef.current,concurrency})});const d=await r.json();if(!r.ok)throw new Error(d.error);onApply(d.plan);if(d.summary?.failed>0){onError(`${d.summary.failed} shot(s) failed. Review the queue and retry.`)}if(d.summary?.queued===0&&d.summary?.running===0){setRunning(false);return}timer.current=setTimeout(tick,5000)}catch(e:any){setRunning(false);onError(e.message||'Production queue tick failed.')}}
 const planRef=useRef(plan); planRef.current=plan
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[])
 const start=async()=>{setRunning(true);try{await queue();timer.current=setTimeout(tick,800)}catch{setRunning(false)}}
 const retryFailed=async()=>{if(!failures.length)return;setRetrying(true);try{await queue();setRunning(true);timer.current=setTimeout(tick,800)}catch(e:any){onError(e.message||'Could not retry failed shots.')}finally{setRetrying(false)}}
 const stop=()=>{setRunning(false);if(timer.current)clearTimeout(timer.current)}
 return <div className="productionbox"><div className="productionhead"><div><h2><Layers3 size={16} style={{verticalAlign:'-3px',marginRight:6}}/>Long-Film Production Queue</h2><p>Generate the film as independent moving-video shots, with bounded parallelism, durable provider operations and resumable progress.</p></div><div className="directorAction"><select value={concurrency} onChange={e=>setConcurrency(Number(e.target.value))} disabled={running}><option value={1}>1 parallel</option><option value={2}>2 parallel</option><option value={3}>3 parallel</option><option value={4}>4 parallel</option><option value={5}>5 parallel</option></select>{running?<button className="generateShot" onClick={stop}><Square size={14}/> Pause</button>:<button className="generateShot" onClick={start}><Play size={14}/> Generate film</button>}</div></div><div className="productionstats"><div className="productionstat"><b>{stats.total}</b><span>Total shots</span></div><div className="productionstat"><b>{stats.q}</b><span>Queued</span></div><div className="productionstat"><b>{stats.r}</b><span>Generating</span></div><div className="productionstat"><b>{stats.c}</b><span>Complete</span></div></div>{stats.f>0&&<div className="productionfailure"><div className="productionrisk"><AlertTriangle size={14}/> {stats.f} failed shot(s) need attention. <button type="button" className="retryFailed" onClick={retryFailed} disabled={retrying}>{retrying?<><LoaderCircle size={13} className="spin"/> Retrying…</>:<><RefreshCw size={13}/> Retry failed</>}</button></div><div className="failurelist">{failures.slice(0,8).map(f=><div className="failureitem" key={f.id}><b>{f.label}</b><span>{f.error}</span></div>)}{failures.length>8&&<small>Showing first 8 failures. Fix the shared provider/configuration error before retrying the rest.</small>}</div></div>} {!stats.total&&<div className="productionrisk">Build the production plan first so the Director can create a shot queue.</div>} {stats.total>0&&stats.c===stats.total&&<div className="productionrisk"><CheckCircle2 size={14}/> All planned shots have generated footage. The film is ready for final editorial/render.</div>}</div>
}
