import {NextResponse} from 'next/server'
import {startVideoGeneration,getVideoGenerationStatus} from '@/lib/video'
import {enforceContinuityPrompt} from '@/lib/continuity'
import {performancePrompt} from '@/lib/performance'
import {updateProductionJob} from '@/lib/db'
import {persistVideoForShot} from '@/lib/project-media'

function flatten(plan:any){const out:any[]=[];for(let ci=0;ci<(plan?.chapters||[]).length;ci++)for(let si=0;si<(plan.chapters[ci].scenes||[]).length;si++)for(let shi=0;shi<(plan.chapters[ci].scenes[si].shots||[]).length;shi++)out.push({ci,si,shi,shot:plan.chapters[ci].scenes[si].shots[shi]});return out}
async function refsFor(plan:any,ci:number,si:number,shi:number,state:any){const shot=plan.chapters[ci].scenes[si].shots[shi];const manifest=shot.referenceManifest?.references||[];const refs=plan.references||[];const images:any[]=[];for(const m of manifest.filter((x:any)=>x.included!==false).sort((a:any,b:any)=>(a.priority??99)-(b.priority??99))){const r=refs.find((x:any)=>x.id===m.referenceId);if(r?.uri)images.push({uri:r.uri,mimeType:r.mimeType,label:r.label,referenceId:r.id,priority:m.priority,role:m.role})}if(!images.length){for(const c of (plan.characters||[]).filter((c:any)=>(state.characterIds||[]).includes(c.id)))for(const ref of (c.referenceImages||[]))if(ref.active!==false)images.push({uri:ref.uri,mimeType:ref.mimeType,label:`${c.name} reference`,referenceId:ref.id,priority:0,role:'identity'})}return images.slice(0,3)}
function summary(plan:any){const xs=flatten(plan);let queued=0,running=0,complete=0,failed=0;for(const x of xs){const s=x.shot.productionJob?.status;if(s==='queued')queued++;else if(s==='running')running++;else if(s==='complete'||x.shot.videoJob?.videoUri)complete++;else if(s==='failed')failed++}return {queued,running,complete,failed,total:xs.length}}
export async function POST(req:Request){try{const b=await req.json();const plan=structuredClone(b.plan);const concurrency=Math.max(1,Math.min(5,Number(b.concurrency)||3));const xs=flatten(plan);const running=xs.filter(x=>x.shot.productionJob?.status==='running');
 for(const x of running){const job=x.shot.productionJob;try{const d:any=await getVideoGenerationStatus(job.operationName);if(d.status==='complete'&&d.videoUri){let uri=d.videoUri,asset:any=null;if(process.env.BLOB_READ_WRITE_TOKEN){asset=await persistVideoForShot(b.projectId||plan.id,x.shot.id,uri,d.mimeType||'video/mp4');uri=asset.uri}x.shot.videoJob={...(x.shot.videoJob||{}),provider:'google-veo',model:process.env.VIDEO_MODEL||'veo-3.1-generate-preview',operationName:job.operationName,videoUri:uri,mediaAssetId:asset ? asset.id : undefined,durable:Boolean(asset),startedAt:job.startedAt||new Date().toISOString()};x.shot.status='complete';job.status='complete';job.completedAt=new Date().toISOString();await updateProductionJob(job.id,{status:'complete',completedAt:job.completedAt})}else if(d.status==='failed'){job.status='failed';job.error=d.error||'Video provider failed.';x.shot.status='failed';await updateProductionJob(job.id,{status:'failed',error:job.error})}}catch(e:any){job.error=e?.message||'Status check failed.'}}
 let slots=concurrency-xs.filter(x=>x.shot.productionJob?.status==='running').length;
 for(const x of xs.filter(x=>x.shot.productionJob?.status==='queued').sort((a,b)=>(a.shot.productionJob.priority??50)-(b.shot.productionJob.priority??50))){if(slots<=0)break;const job=x.shot.productionJob;try{const enforced=enforceContinuityPrompt(plan,x.ci,x.si,x.shi,x.shot.prompt);let prompt=enforced.prompt;if(x.shot.performance)prompt=performancePrompt(plan,x.ci,x.si,x.shi,x.shot.performance);const referenceImages=await refsFor(plan,x.ci,x.si,x.shi,enforced.state);const d=await startVideoGeneration({prompt,aspectRatio:'16:9',resolution:'1080p',duration:8,referenceImages});job.status='running';job.startedAt=new Date().toISOString();job.attempts=(job.attempts||0)+1;job.operationName=d.operationName;x.shot.videoJob={...d,startedAt:job.startedAt};x.shot.status='generating';await updateProductionJob(job.id,{status:'running',attempts:job.attempts,operationName:d.operationName,provider:d.provider,model:d.model,startedAt:job.startedAt});slots--}catch(e:any){job.attempts=(job.attempts||0)+1;job.error=e?.message||'Generation start failed.';if(job.attempts<3){job.status='queued'}else{job.status='failed';x.shot.status='failed'}await updateProductionJob(job.id,{status:job.status,attempts:job.attempts,error:job.error})}}
 const finalSummary=summary(plan); const failures=xs.filter(x=>x.shot.productionJob?.status==='failed').map(x=>({shotId:x.shot.id,error:x.shot.productionJob?.error||'Video generation failed.'})); return NextResponse.json({plan,summary:finalSummary,failures})}catch(e:any){return NextResponse.json({error:e?.message||'Production tick failed.'},{status:500})}}
