import type {DirectorPlan, Timeline} from './schemas'

export type YouTubeChapter={time:string;title:string;seconds:number}
export type YouTubePackage={version:1;title:string;description:string;tags:string[];category:string;language:string;privacy:'private'|'unlisted'|'public';chapters:YouTubeChapter[];thumbnail:{titleText:string;concept:string;prompt:string;aspectRatio:'16:9';safeArea:string};subtitle:{format:'srt';text:string};metadata:{madeForKids:false;containsSyntheticMedia:boolean;aiDisclosureRecommended:boolean};generatedAt:string}

function fmt(sec:number){const s=Math.max(0,Math.floor(sec));const h=Math.floor(s/3600);const m=Math.floor((s%3600)/60);const x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`}
function chapters(plan:DirectorPlan,timeline?:Timeline){const out:YouTubeChapter[]=[];let cursor=0;for(const ch of plan.chapters||[]){const duration=(ch.scenes||[]).reduce((a,s)=>a+(s.shots||[]).reduce((b,sh)=>b+Number(sh.duration||0),0),0);out.push({time:fmt(cursor),title:ch.title,seconds:cursor});cursor+=duration}return out.filter((x,i)=>i===0||x.seconds>0)}
function slugTags(plan:DirectorPlan){const words=`${plan.title} ${plan.genre} ${plan.visualStyle}`.toLowerCase().match(/[a-z0-9]+/g)||[];return Array.from(new Set([...words,'AI film','AI filmmaking','cinematic documentary','artificial intelligence'])) .slice(0,15)}
export function buildYouTubePackage(plan:DirectorPlan,timeline?:Timeline):YouTubePackage{const ch=chapters(plan,timeline);const chapterText=ch.length?`\n\nCHAPTERS\n${ch.map(x=>`${x.time} — ${x.title}`).join('\n')}`:'';const desc=`${plan.logline}\n\nCreated in AI Film Studio with AI-generated moving footage, natural voice performance, original music and cinematic sound design.\n\n${plan.visualStyle ? `Visual style: ${plan.visualStyle}.\n` : ''}${chapterText}`.trim();return {version:1,title:plan.title,description:desc,tags:slugTags(plan),category:'Film & Animation',language:'en',privacy:'private',chapters:ch,thumbnail:{titleText:plan.title.slice(0,48),concept:`Cinematic hero image representing the central conflict of ${plan.title}, with one clear focal subject, dramatic depth, premium film-poster composition, no clutter, no tiny text.`,prompt:`16:9 YouTube thumbnail, cinematic film still, ${plan.visualStyle||'premium cinematic realism'}, central subject from the story, dramatic lighting, strong depth, high contrast, emotionally compelling, clean negative space for title, photorealistic, no watermark, no logos, no distorted faces, no extra fingers`,aspectRatio:'16:9',safeArea:'Keep important faces and text inside the central 80% safe area.'},subtitle:{format:'srt',text:buildSrt(plan.narrationScript||'',timeline?.duration||plan.durationMinutes*60)},metadata:{madeForKids:false,containsSyntheticMedia:true,aiDisclosureRecommended:true},generatedAt:new Date().toISOString()}}
export function buildSrt(text:string,total:number){const parts=text.replace(/\s+/g,' ').trim().match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[];if(!parts.length)return '';const weights=parts.map(p=>Math.max(1,p.trim().split(/\s+/).length));const sum=weights.reduce((a,b)=>a+b,0);let cur=0;const ts=(x:number)=>{const ms=Math.round((x-Math.floor(x))*1000),t=Math.floor(x);return `${String(Math.floor(t/3600)).padStart(2,'0')}:${String(Math.floor((t%3600)/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')},${String(ms).padStart(3,'0')}`};return parts.map((p,i)=>{const d=total*(weights[i]/sum);const a=cur;cur=Math.min(total,cur+d);return `${i+1}\n${ts(a)} --> ${ts(cur)}\n${p.trim()}\n`}).join('\n')}
