'use client'
import { useMemo, useState } from 'react'
import { Clapperboard, Download, GripVertical, Scissors, Sparkles, Volume2, VolumeX, Wand2, ChevronDown } from 'lucide-react'
import type { DirectorPlan, Timeline, TimelineClip } from '@/lib/schemas'
import { buildTimeline } from '@/lib/timeline'

type Props={plan:DirectorPlan;timeline?:Timeline;onChange:(timeline:Timeline)=>void;onError:(message:string)=>void}
const transitions:TimelineClip['transition'][]=['cut','dissolve','fade','fadeblack','fadewhite','wipeleft','slideright','smoothleft']
const transitionLabel=(x:string)=>x==='fadeblack'?'Fade to black':x==='fadewhite'?'Fade to white':x==='wipeleft'?'Wipe left':x==='slideright'?'Slide right':x==='smoothleft'?'Smooth slide':x[0].toUpperCase()+x.slice(1)

export default function TimelineEditor({plan,timeline,onChange,onError}:Props){
 const initial=useMemo(()=>timeline||buildTimeline(plan),[plan,timeline]); const [local,setLocal]=useState<Timeline>(initial); const [selected,setSelected]=useState<string|null>(null); const [aiBusy,setAiBusy]=useState(false)
 const setTimeline=(next:Timeline)=>{setLocal(next);onChange(next)}; const videos=local.clips.filter(c=>c.kind==='video').sort((a,b)=>a.start-b.start); const max=Math.max(local.duration,1); const selectedClip=local.clips.find(c=>c.id===selected)
 const updateClip=(id:string,patch:Partial<TimelineClip>)=>setTimeline({...local,clips:local.clips.map(c=>c.id===id?{...c,...patch}:c)})
 const move=(id:string,d:-1|1)=>{const v=videos.slice(),i=v.findIndex(c=>c.id===id),n=i+d;if(i<0||n<0||n>=v.length)return;[v[i],v[n]]=[v[n],v[i]];let cur=0;const reordered=v.map(c=>{const x={...c,start:cur};cur+=x.duration;return x});setTimeline({...local,duration:cur,version:2,clips:[...reordered,...local.clips.filter(c=>c.kind!=='video')]})}
 const split=async()=>{if(!selectedClip||selectedClip.kind!=='video')return;try{const r=await fetch('/api/editor/split',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({timeline:local,clipId:selectedClip.id,atSeconds:selectedClip.start+selectedClip.duration/2})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTimeline(d.timeline);setSelected(`${selectedClip.id}-a`)}catch(e:any){onError(e.message||'Split failed.')}}
 const aiCut=async()=>{setAiBusy(true);try{const r=await fetch('/api/editor/ai-cut',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan:{...plan,timeline:local}})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTimeline(d.timeline)}catch(e:any){onError(e.message||'AI edit failed.')}finally{setAiBusy(false)}}
 const prepare=async()=>{try{const r=await fetch('/api/editor/edl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({timeline:local})});const d=await r.json();if(!r.ok)throw new Error(d.error);const b=new Blob([JSON.stringify(d.edl,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`${plan.title.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-edit.json`;a.click();URL.revokeObjectURL(u)}catch(e:any){onError(e.message||'Could not prepare edit.')}}
 return <section className="timelineStudio"><div className="timelineHead"><div><h2><Clapperboard size={17}/> Professional AI Editor</h2><p>Non-destructive cutting, scene-aware transitions, trim controls and edit-decision export.</p></div><div className="timelineActions"><button className="ghost small" disabled={aiBusy} onClick={aiCut}><Wand2 size={14}/>{aiBusy?' Editing…':' AI cut'}</button><button className="ghost small" onClick={split}><Scissors size={14}/> Split</button><button className="generateShot" onClick={prepare}><Download size={14}/> EDL</button></div></div>
 <div className="timelineToolbar"><span><Sparkles size={14}/> {videos.length} video clips</span><span>{Math.round(local.duration)}s total</span><span>{local.aspectRatio} · {local.frameRate}fps</span><span>v{local.version}</span></div>
 <div className="timelineRuler"><div className="rulerLine"/>{[0,.25,.5,.75,1].map(v=><span key={v} style={{left:`${v*100}%`}}>{Math.round(max*v)}s</span>)}</div>
 <div className="timelineTracks"><div className="trackLabel">VIDEO</div><div className="trackLane videoLane">{videos.map((c,i)=><button key={c.id} className={`timelineClip ${selected===c.id?'selected':''}`} style={{left:`${c.start/max*100}%`,width:`${Math.max(c.duration/max*100,2)}%`}} onClick={()=>setSelected(c.id)}><GripVertical size={12}/><b>{i+1}</b><span>{c.label}</span>{c.transition!=='cut'&&<em>{c.transition}</em>}</button>)}</div><div className="trackLabel">AUDIO</div><div className="trackLane audioLane">{local.clips.filter(c=>c.kind!=='video').map(c=><button key={c.id} className={`audioTimelineClip ${selected===c.id?'selected':''}`} style={{left:`${c.start/max*100}%`,width:`${Math.max(c.duration/max*100,4)}%`}} onClick={()=>setSelected(c.id)}><span>{c.kind.toUpperCase()} · {c.label}</span></button>)}</div><div className="playhead" style={{left:`${Math.min(local.playhead/max,1)*100}%`}}/></div>
 {selectedClip&&<div className="clipInspector"><div><b><Scissors size={14}/> Clip Inspector</b><span>{selectedClip.label}</span></div><label>Start <input type="number" min="0" step="0.1" value={selectedClip.start} onChange={e=>updateClip(selectedClip.id,{start:Math.max(0,Number(e.target.value))})}/></label><label>Duration <input type="number" min="0.5" step="0.5" value={selectedClip.duration} onChange={e=>updateClip(selectedClip.id,{duration:Math.max(.5,Number(e.target.value)),trimEnd:selectedClip.trimStart+Math.max(.5,Number(e.target.value))})}/></label>{selectedClip.kind==='video'&&<><label>Transition <select value={selectedClip.transition} onChange={e=>updateClip(selectedClip.id,{transition:e.target.value as any,transitionDuration:e.target.value==='cut'?0:Math.min(selectedClip.duration/2,.5)})}>{transitions.map(t=><option key={t} value={t}>{transitionLabel(t)}</option>)}</select></label>{selectedClip.transition!=='cut'&&<label>Length <input type="number" min="0.05" max="2" step="0.05" value={selectedClip.transitionDuration??0} onChange={e=>updateClip(selectedClip.id,{transitionDuration:Number(e.target.value)})}/></label>}<button className="iconButton" onClick={()=>move(selectedClip.id,-1)}>←</button><button className="iconButton" onClick={()=>move(selectedClip.id,1)}>→</button></>}<label>Volume <input type="range" min="0" max="1" step=".01" value={selectedClip.volume} onChange={e=>updateClip(selectedClip.id,{volume:Number(e.target.value)})}/></label><button className="iconButton" onClick={()=>updateClip(selectedClip.id,{muted:!selectedClip.muted})}>{selectedClip.muted?<VolumeX size={15}/>:<Volume2 size={15}/>}</button></div>}
 <div className="timelineNote"><ChevronDown size={13}/> AI Cut uses film context to choose restrained transitions; manual controls remain non-destructive. Final rendering honors supported transition metadata.</div></section>
}
