'use client'
import {useState} from 'react'
import {Download,LoaderCircle,Package,RefreshCw} from 'lucide-react'
import type {DirectorPlan,Timeline} from '@/lib/schemas'
import {buildYouTubePackage} from '@/lib/youtube-package'
export default function YouTubePackage({projectId,plan,timeline,onError}:{projectId:string;plan:DirectorPlan;timeline?:Timeline;onError:(m:string)=>void}){
 const [pkg,setPkg]=useState<any>(null);const [busy,setBusy]=useState(false)
 const build=async()=>{setBusy(true);try{const r=await fetch('/api/youtube/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,timeline})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPkg(d.package)}catch(e:any){onError(e.message||'Could not build YouTube package.')}finally{setBusy(false)}}
 const local=()=>setPkg(buildYouTubePackage(plan,timeline))
 const download=(name:string,text:string,type:string)=>{const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
 const slug=(x:string)=>x.replace(/[^a-z0-9]+/gi,'-').toLowerCase().replace(/^-|-$/g,'')||'film'
 return <section className="youtubeBox"><div className="timelineHead"><div><h2><Package size={17}/> YouTube Publishing Package</h2><p>One production handoff containing title, description, tags, chapters, subtitles, thumbnail direction and synthetic-media metadata.</p></div><span className="voicebadge">YouTube Ready</span></div><div className="renderActions"><button className="generateShot" onClick={build} disabled={busy}>{busy?<><LoaderCircle size={14} className="spin"/> Building package…</>:<><Package size={14}/> Build publishing package</>}</button><button className="ghost" onClick={local} disabled={busy}><RefreshCw size={14}/> Build locally</button></div>{pkg&&<><div className="ytgrid"><label>Title<textarea value={pkg.title} onChange={e=>setPkg({...pkg,title:e.target.value})}/></label><label>Description<textarea value={pkg.description} onChange={e=>setPkg({...pkg,description:e.target.value})}/></label><label>Tags<input value={pkg.tags.join(', ')} onChange={e=>setPkg({...pkg,tags:e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean)})}/></label><div className="ytcard"><b>Chapters</b>{pkg.chapters.map((x:any,i:number)=><span key={i}>{x.time} — {x.title}</span>)}</div><div className="ytcard"><b>Thumbnail direction</b><span>{pkg.thumbnail.concept}</span><small>{pkg.thumbnail.prompt}</small></div><div className="ytcard"><b>AI disclosure</b><span>{pkg.metadata.aiDisclosureRecommended?'Recommended: disclose synthetic/AI-generated elements in the upload workflow.':'No disclosure recommendation.'}</span></div></div><div className="renderActions"><button className="ghost" onClick={()=>download(`${slug(pkg.title)}-youtube-description.txt`,pkg.description,'text/plain')}><Download size={14}/> Description</button><button className="ghost" onClick={()=>download(`${slug(pkg.title)}-tags.txt`,pkg.tags.join(', '),'text/plain')}><Download size={14}/> Tags</button><button className="ghost" onClick={()=>download(`${slug(pkg.title)}-chapters.txt`,pkg.chapters.map((x:any)=>`${x.time} — ${x.title}`).join('\n'),'text/plain')}><Download size={14}/> Chapters</button><button className="ghost" onClick={()=>download(`${slug(pkg.title)}-subtitles.srt`,pkg.subtitle.text,'application/x-subrip')}><Download size={14}/> SRT subtitles</button><button className="ghost" onClick={()=>download(`${slug(pkg.title)}-youtube-package.json`,JSON.stringify(pkg,null,2),'application/json')}><Download size={14}/> Full JSON</button></div></>}</section>
}
